#set the prefix to Ctrl-a
set -g prefix C-a

# Allow sending Ctrl-a to other apps by pressing it twice
bind C-a send-prefix

# set -g mouse on # scroll history using mouse

set -g history-limit 20000 # history when scrolling back
setw -g mode-keys vi # vi style navigation while using copy mode
