#set the prefix to Ctrl-a
set -g prefix C-a

# Allow sending Ctrl-a to other apps by pressing it twice
bind C-a send-prefix

# set -g mouse off # scroll history using mouse

set -g history-limit 20000 # history when scrolling back
setw -g mode-keys vi # vi style navigation while using copy mode

# copy tmux buffer to clipboard
set -s set-clipboard on

# Add ressurect plugin for tmux session to survive system reboot
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-processes '"~claude->claude *"'

# Auto-install tpm and plugins on a new machine
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

